### ISSUE TITLE
model_gene_var stopped working

### ISSUE THREAD

**Issue by lambdamoses** [pmelsted/voyagerpy#25]
I'm rerunning some code that used to work, which was used to make figures for the preprint. Here's a colab notebook to reproduce the error: https://colab.research.google.com/drive/1T5-3AI2rYsWR-bqZzaF2BmGXyOU3M0in?usp=sharing

The gene names are the Ensembl IDs so there shouldn't be duplicates. After data normalization, this code

```
gene_var = vp.utils.model_gene_var(adata.layers['logcounts'], gene_names=adata.var_names)
```

gives this error from pandas:

```
InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```

Pandas version is 1.5.3

**Comment by lambdamoses** [comment]
It seems that this only occurs when the Visium data is in the h5 format. It still worked when the data is mtx.

**Comment by lambdamoses** [comment]
It's probably because there are duplicate values in the mean log counts per gene. Given that many genes have low counts, it's not unusual to get duplicate means. The R function you were trying to translate is not sensitive to duplicates (https://github.com/MarioniLab/scran/blob/f238890d5642dfb8062cf0254e0257fd28c5f28d/R/fitTrendVar.R#L188-L193). But then I wonder why it used to work. Could be caused by a dependency update.

**Comment by lambdamoses** [comment]
I think the problem comes from `vp.utils.log_norm_counts`, which weirdly produces integer values, causing duplicate values in the mean, which caused this error, and it's only been doing so since quite recently, at least after July.

**Comment by lambdamoses** [comment]
I think it's caused by the new version of `log_norm_counts`. The error disappeared when I installed v0.1.0 of voyagerpy. Which is still kind of weird because it would work when I copy and paste the code out of `log_norm_counts`, but that's not in a debugger.

**Comment by peturhelgi** [comment]
> I think the problem comes from `vp.utils.log_norm_counts`, which weirdly produces integer values, causing duplicate values in the mean, which caused this error, and it's only been doing so since quite recently, at least after July.

I get the same error as you do, and the normalized counts are indeed integer-valued, though the datatype of the matrix is float64. 

I think this must be because when you slice an AnnData object, you get a view of it instead of a new AnnData object. If you copy the slice, you should not get an error and the normalized log counts are real-valued:

```python
adata = adata[adata.obs["in_tissue"] == True].copy()   # <- make sure you copy the object.
vp.utils.log_norm_counts(adata, inplace=True)
adata.layers['logcounts'] = adata.X.copy()
adata.layers['logcounts'].A
```

```python
array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.9035852 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.99946154],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.36367765],
       [0.        , 0.        , 1.30454946, ..., 0.        , 0.        ,
        1.30454946],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.70236466]])
```
